# coding: utf-8

"""
    

     # Basic sequence  - Register a sensor system - `POST /ss` - Add one or more data streams to the sensor system - `POST /ss/{sysid}` - Add data stream observations - `POST /ss/{sysid}/{strid}/obs`        

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.system_api import SystemApi


class TestSystemApi(unittest.TestCase):
    """ SystemApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.system_api.SystemApi()

    def tearDown(self):
        pass

    def test_delete_system(self):
        """
        Test case for delete_system

        Unregister a sensor system
        """
        pass

    def test_get_system(self):
        """
        Test case for get_system

        Get a sensor system
        """
        pass

    def test_list_systems(self):
        """
        Test case for list_systems

        List all registered sensor systems
        """
        pass

    def test_register_stream(self):
        """
        Test case for register_stream

        Add a data stream
        """
        pass

    def test_register_system(self):
        """
        Test case for register_system

        Register sensor system
        """
        pass

    def test_update_system(self):
        """
        Test case for update_system

        Update a sensor system
        """
        pass


if __name__ == '__main__':
    unittest.main()
