# coding: utf-8

"""
    Gpdviz REST API

    The Gpdviz REST API deals with three main kinds of resources: sensor systems, data streams, and observations.

    OpenAPI spec version: 0.4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.variable_definition_api import VariableDefinitionApi


class TestVariableDefinitionApi(unittest.TestCase):
    """ VariableDefinitionApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.variable_definition_api.VariableDefinitionApi()

    def tearDown(self):
        pass

    def test_add_variable_def(self):
        """
        Test case for add_variable_def

        Add variable definition
        """
        pass


if __name__ == '__main__':
    unittest.main()
