# coding: utf-8

"""
    Gpdviz REST API

    The Gpdviz REST API deals with three main kinds of resources: sensor systems, data streams, and observations.

    OpenAPI spec version: 0.4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.variable_def_summary import VariableDefSummary


class TestVariableDefSummary(unittest.TestCase):
    """ VariableDefSummary unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVariableDefSummary(self):
        """
        Test VariableDefSummary
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.variable_def_summary.VariableDefSummary()
        pass


if __name__ == '__main__':
    unittest.main()
