# coding: utf-8

"""
    

    gpdviz API

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.variable_def import VariableDef


class TestVariableDef(unittest.TestCase):
    """ VariableDef unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVariableDef(self):
        """
        Test VariableDef
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.variable_def.VariableDef()
        pass


if __name__ == '__main__':
    unittest.main()
