# coding: utf-8

"""
    

     # Basic sequence  - Register a sensor system - `POST /ss` - Add one or more data streams to the sensor system - `POST /ss/{sysid}` - Add data stream observations - `POST /ss/{sysid}/{strid}/obs`        

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.stream_api import StreamApi


class TestStreamApi(unittest.TestCase):
    """ StreamApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.stream_api.StreamApi()

    def tearDown(self):
        pass

    def test_delete_stream(self):
        """
        Test case for delete_stream

        Delete a data stream
        """
        pass

    def test_get_stream(self):
        """
        Test case for get_stream

        Get a data stream
        """
        pass

    def test_register_stream(self):
        """
        Test case for register_stream

        Add a data stream
        """
        pass


if __name__ == '__main__':
    unittest.main()
