# coding: utf-8

"""
    

     # Basic sequence  - Register a sensor system - `POST /ss` - Add one or more data streams to the sensor system - `POST /ss/{sysid}` - Add data stream observations - `POST /ss/{sysid}/{strid}/obs`        

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.system_api import SystemApi


class TestSystemApi(unittest.TestCase):
    """ SystemApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.system_api.SystemApi()

    def tearDown(self):
        pass

    def test_add_ss(self):
        """
        Test case for add_ss

        Register sensor system
        """
        pass

    def test_add_str(self):
        """
        Test case for add_str

        Add a data stream
        """
        pass

    def test_delete_ss(self):
        """
        Test case for delete_ss

        Unregister a sensor system
        """
        pass

    def test_get_ss(self):
        """
        Test case for get_ss

        Get a sensor system
        """
        pass

    def test_list_ss(self):
        """
        Test case for list_ss

        List all registered sensor systems
        """
        pass

    def test_update_ss(self):
        """
        Test case for update_ss

        Update a sensor system
        """
        pass


if __name__ == '__main__':
    unittest.main()
