# coding: utf-8

"""
    

    gpdviz API

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.ss_update import SSUpdate


class TestSSUpdate(unittest.TestCase):
    """ SSUpdate unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSSUpdate(self):
        """
        Test SSUpdate
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.ss_update.SSUpdate()
        pass


if __name__ == '__main__':
    unittest.main()
