# coding: utf-8

"""
    

    gpdviz API

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.data_stream_api import DataStreamApi


class TestDataStreamApi(unittest.TestCase):
    """ DataStreamApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.data_stream_api.DataStreamApi()

    def tearDown(self):
        pass

    def test_add_str(self):
        """
        Test case for add_str

        Add a stream
        """
        pass

    def test_delete_str(self):
        """
        Test case for delete_str

        Delete a data stream
        """
        pass

    def test_get_str(self):
        """
        Test case for get_str

        Get a data stream
        """
        pass


if __name__ == '__main__':
    unittest.main()
