# coding: utf-8

"""
    

     # Basic sequence  - Register a sensor system - `POST /ss` - Add one or more data streams to the sensor system - `POST /ss/{sysid}` - Add data stream observations - `POST /ss/{sysid}/{strid}/obs`        

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Feature(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'JsValue',
        'properties': 'dict(str, JsValue)',
        'geometry': 'Geometry'
    }

    attribute_map = {
        'id': 'id',
        'properties': 'properties',
        'geometry': 'geometry'
    }

    def __init__(self, id=None, properties=None, geometry=None):
        """
        Feature - a model defined in Swagger
        """

        self._id = None
        self._properties = None
        self._geometry = None

        if id is not None:
          self.id = id
        self.properties = properties
        self.geometry = geometry

    @property
    def id(self):
        """
        Gets the id of this Feature.

        :return: The id of this Feature.
        :rtype: JsValue
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Feature.

        :param id: The id of this Feature.
        :type: JsValue
        """

        self._id = id

    @property
    def properties(self):
        """
        Gets the properties of this Feature.

        :return: The properties of this Feature.
        :rtype: dict(str, JsValue)
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """
        Sets the properties of this Feature.

        :param properties: The properties of this Feature.
        :type: dict(str, JsValue)
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")

        self._properties = properties

    @property
    def geometry(self):
        """
        Gets the geometry of this Feature.

        :return: The geometry of this Feature.
        :rtype: Geometry
        """
        return self._geometry

    @geometry.setter
    def geometry(self, geometry):
        """
        Sets the geometry of this Feature.

        :param geometry: The geometry of this Feature.
        :type: Geometry
        """
        if geometry is None:
            raise ValueError("Invalid value for `geometry`, must not be `None`")

        self._geometry = geometry

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Feature):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
