# coding: utf-8

"""
    Gpdviz REST API

    The Gpdviz REST API deals with three main kinds of resources: sensor systems, data streams, and observations.

    OpenAPI spec version: 0.4.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SensorSystemSummary(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sysid': 'str',
        'name': 'str',
        'description': 'str',
        'push_events': 'float',
        'center': 'LatLon',
        'stream_ids': 'list[str]'
    }

    attribute_map = {
        'sysid': 'sysid',
        'name': 'name',
        'description': 'description',
        'push_events': 'pushEvents',
        'center': 'center',
        'stream_ids': 'streamIds'
    }

    def __init__(self, sysid=None, name=None, description=None, push_events=None, center=None, stream_ids=None):
        """
        SensorSystemSummary - a model defined in Swagger
        """

        self._sysid = None
        self._name = None
        self._description = None
        self._push_events = None
        self._center = None
        self._stream_ids = None

        self.sysid = sysid
        if name is not None:
          self.name = name
        if description is not None:
          self.description = description
        if push_events is not None:
          self.push_events = push_events
        if center is not None:
          self.center = center
        self.stream_ids = stream_ids

    @property
    def sysid(self):
        """
        Gets the sysid of this SensorSystemSummary.

        :return: The sysid of this SensorSystemSummary.
        :rtype: str
        """
        return self._sysid

    @sysid.setter
    def sysid(self, sysid):
        """
        Sets the sysid of this SensorSystemSummary.

        :param sysid: The sysid of this SensorSystemSummary.
        :type: str
        """
        if sysid is None:
            raise ValueError("Invalid value for `sysid`, must not be `None`")

        self._sysid = sysid

    @property
    def name(self):
        """
        Gets the name of this SensorSystemSummary.

        :return: The name of this SensorSystemSummary.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this SensorSystemSummary.

        :param name: The name of this SensorSystemSummary.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this SensorSystemSummary.

        :return: The description of this SensorSystemSummary.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this SensorSystemSummary.

        :param description: The description of this SensorSystemSummary.
        :type: str
        """

        self._description = description

    @property
    def push_events(self):
        """
        Gets the push_events of this SensorSystemSummary.

        :return: The push_events of this SensorSystemSummary.
        :rtype: float
        """
        return self._push_events

    @push_events.setter
    def push_events(self, push_events):
        """
        Sets the push_events of this SensorSystemSummary.

        :param push_events: The push_events of this SensorSystemSummary.
        :type: float
        """

        self._push_events = push_events

    @property
    def center(self):
        """
        Gets the center of this SensorSystemSummary.

        :return: The center of this SensorSystemSummary.
        :rtype: LatLon
        """
        return self._center

    @center.setter
    def center(self, center):
        """
        Sets the center of this SensorSystemSummary.

        :param center: The center of this SensorSystemSummary.
        :type: LatLon
        """

        self._center = center

    @property
    def stream_ids(self):
        """
        Gets the stream_ids of this SensorSystemSummary.

        :return: The stream_ids of this SensorSystemSummary.
        :rtype: list[str]
        """
        return self._stream_ids

    @stream_ids.setter
    def stream_ids(self, stream_ids):
        """
        Sets the stream_ids of this SensorSystemSummary.

        :param stream_ids: The stream_ids of this SensorSystemSummary.
        :type: list[str]
        """
        if stream_ids is None:
            raise ValueError("Invalid value for `stream_ids`, must not be `None`")

        self._stream_ids = stream_ids

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SensorSystemSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
