# coding: utf-8

"""
    Gpdviz REST API

    The Gpdviz REST API deals with three kinds of resources: sensor systems, data streams, and observations.

    OpenAPI spec version: 0.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class VariableDef(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'units': 'str',
        'chart_style': 'object'
    }

    attribute_map = {
        'name': 'name',
        'units': 'units',
        'chart_style': 'chartStyle'
    }

    def __init__(self, name=None, units=None, chart_style=None):
        """
        VariableDef - a model defined in Swagger
        """

        self._name = None
        self._units = None
        self._chart_style = None

        self.name = name
        if units is not None:
          self.units = units
        if chart_style is not None:
          self.chart_style = chart_style

    @property
    def name(self):
        """
        Gets the name of this VariableDef.

        :return: The name of this VariableDef.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this VariableDef.

        :param name: The name of this VariableDef.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def units(self):
        """
        Gets the units of this VariableDef.

        :return: The units of this VariableDef.
        :rtype: str
        """
        return self._units

    @units.setter
    def units(self, units):
        """
        Sets the units of this VariableDef.

        :param units: The units of this VariableDef.
        :type: str
        """

        self._units = units

    @property
    def chart_style(self):
        """
        Gets the chart_style of this VariableDef.

        :return: The chart_style of this VariableDef.
        :rtype: object
        """
        return self._chart_style

    @chart_style.setter
    def chart_style(self, chart_style):
        """
        Sets the chart_style of this VariableDef.

        :param chart_style: The chart_style of this VariableDef.
        :type: object
        """

        self._chart_style = chart_style

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, VariableDef):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
